#!/bin/sh
#SBATCH --job-name="UmbSam"
#SBATCH --output="UmbSam.%j.%N.out"
#SBATCH --partition=GPU-shared
#SBATCH --gpus=v100-32:1
#SBATCH -n 5
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=jdepaoloboisvert@hawk.iit.edu
#SBATCH --account=mcb160011p
#SBATCH -t 24:00:00

source ~/.bashrc

conda activate openmmtools

cd $SLURM_SUBMIT_DIR

echo EQUIL JOB for $2 $3
python UmbSam_EQUILIBRATION.py $1 $2 $3 $4 
