#!/bin/bash
#SBATCH --job-name="UmbSam"
#SBATCH --output="UmbSam.%j.%N.out"
#SBATCH --partition=gpu-shared
#SBATCH --gpus=1
#SBATCH --nodes=1
#SBATCH --ntasks=5
#SBATCH --mem=80G
#SBATCH --account=iit122
#SBATCH -t 48:00:00
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=dcooper6@hawk.iit.edu

source ~/.bashrc

conda activate replica

cd $SLURM_SUBMIT_DIR

echo EQUIL JOB for $2 $3
python UmbSam_EQUILIBRATION.py $1 $2 $3 $4 
