#!/bin/bash
#SBATCH --job-name="EnerExtr"
#SBATCH --output="EnerExtr.%j.%N.out"
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --mem=32GB
#SBATCH --account=iit122
#SBATCH -t 48:00:00
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=jdepaoloboisvert@hawk.iit.edu

source ~/.bashrc

conda activate replica

cd $SLURM_SUBMIT_DIR
#INPUT_DIR PDB_FN SAVE_DIR 
python get_energies_of_endstates.py $1 $2 $3
